apps/samples/urls.py
from django.urls import path

from samples import views

urlpatterns = [
    path('samples/', views.SampleListView.as_view(), name='sample-list'),
    path('samples/search/<int:pk>/', views.HSDBRecord.as_view(), name='compound-record'),
    path('samples/search/', views.HSDBSearch.as_view(), name='compound-search'),
    path('samples/help/', views.SampleHelp.as_view(), name='sample-help'),
    path('samples/field/', views.SampleField.as_view(), name='sample-field-root'),
    path('samples/field/<int:pk>/<str:field_name>/', views.SampleField.as_view(), name='sample-field'),
    path('samples/hazards/<int:pk>/<str:field_name>/', views.SampleHazards.as_view(), name='sample-hazards'),
    path('samples/permissions/<int:pk>/<str:field_name>/', views.SamplePermissions.as_view(), name='sample-permissions'),

    path('safety/permissions/', views.SafetyPermissionList.as_view(), name='safety-permission-list'),
    path('safety/permissions/<int:pk>/edit/', views.EditSafetyPermission.as_view(), name='edit-safety-permission'),
    path('safety/permissions/new/', views.AddSafetyPermission.as_view(), name='add-safety-permission'),
    path('safety/permissions/<int:pk>/delete/', views.DeleteSafetyPermission.as_view(), name='delete-safety-permission'),

    path('safety/substances/', views.HazardousSubstanceList.as_view(), name='hazardous-substance-list'),
    path('safety/substances/<int:pk>/edit/', views.EditHazardousSubstance.as_view(), name='edit-hazardous-substance'),
    path('safety/substances/new/', views.AddHazardousSubstance.as_view(), name='add-hazardous-substance'),
    path('safety/substances/<int:pk>/delete/', views.DeleteHazardousSubstance.as_view(), name='delete-hazardous-substance'),

]

usonline/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from django.urls import reverse_lazy
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static
from misc.utils import iterload

admin.site.site_header = "User Services Online"

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('user-dashboard'), permanent=False)),
    path('', include('users.urls')),

    path('', include('proposals.urls')),
    path('', include('agreements.urls')),
    path('', include('publications.urls')),
    path('', include('beamlines.urls')),
    path('', include('scheduler.urls')),
    path('', include('projects.urls')),
    path('', include('samples.urls')),
    path('forms/', include('dynforms.urls')),
    path('reports/', include('reportcraft.urls')),
    path('messages/', include('notifier.urls')),
    path('', include('weather.urls')),
    path('', include('surveys.urls')),
    path('', include('isocron.urls')),

    path('admin/logout/', LogoutView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('misc.urls')),
]

# API URLS
for api_url in iterload('api_urls'):
    urlpatterns += [path('api/v1/', include(api_url))]

# User URLs
for user_url in iterload('user_urls'):
    urlpatterns += [path('user/', include(user_url))]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('500/', TemplateView.as_view(template_name='500.html'), name='error-500'),
        path('503/', TemplateView.as_view(template_name='503.html'), name='error-503'),
        path('404/', TemplateView.as_view(template_name='404.html'), name='error-404'),
        path('403/', TemplateView.as_view(template_name='403.html'), name='error-403'),
    ]

apps/samples/models.py
from __future__ import annotations

import re

from django.conf import settings
from django.db import models
from django.utils.translation import gettext as _
from model_utils import Choices
from model_utils.models import TimeStampedModel

from . import utils
from misc.models import GenericContentMixin

User = getattr(settings, "AUTH_USER_MODEL")

SIGNALS = Choices(
    ('warning', _('Warning')),
    ('danger', _('Danger')),
)

WASTE_TYPES = Choices(
    (_('Biological Wastes'), [
        ('bio_solids', _('Biological petri dishes, pipette tips, etc.')),
        ('bio_liquids', _('Biological liquids, cultures, etc')),
        ('bio_sharps', _('Biological syringes, blades, glass etc.')),
        ('bio_tissues', _('Biological, tissues, etc.')),
    ]),
    (_('Others'), [
        ('radioactive', _('Radioactive Waste')),
        ('chemical', _('Solid/Liquid Chemical Waste')),
        ('hazardous_gas', _('Hazardous gases')),
        ('nonhazardous', _('Non-Hazardous Waste')),
    ]),
)


class CodeManager(models.Manager):
    def get_by_natural_key(self, code):
        return self.get(code=code)


class HStatement(TimeStampedModel):
    code = models.CharField(max_length=20, unique=True, db_index=True)
    text = models.CharField(max_length=255)
    objects = CodeManager()

    def __str__(self):
        return "{}: {}".format(self.code, self.text)

    def natural_key(self):
        return self.code,  # tuple


class PrecautionManager(CodeManager):
    def for_hazards(self, hazards: list | models.QuerySet) -> models.QuerySet:
        """
        Return precautions for a list of hazards.
        """

        if isinstance(hazards, list):
            hazards = Hazard.objects.filter(pk__in=hazards)

        # select precautions from the hazards
        precautions = self.filter(
            pk__in=hazards.values_list('precautions__pk', flat=True)
        ).distinct().order_by('code')

        # remove precautions already present in combined codes
        removed_codes = {
            code
            for codes in precautions.filter(code__contains="+").values_list('code', flat=True)
            for code in codes.split('+')
        }
        return precautions.exclude(code__in=removed_codes).distinct()


class PStatement(TimeStampedModel):
    code = models.CharField(max_length=20, unique=True, db_index=True)
    text = models.CharField(max_length=255)
    objects = PrecautionManager()

    def __str__(self):
        return f"{self.code}: {self.text}"

    def natural_key(self):
        return self.code,  # tuple


class Pictogram(TimeStampedModel):
    name = models.CharField(max_length=100)
    description = models.TextField()
    code = models.CharField(max_length=20)
    objects = CodeManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return self.code,


class HazardManager(models.Manager):
    def get_by_natural_key(self, signal, hazard):
        return self.get(signal=signal, hazard__code=hazard)


# initial source of information Sigma-Aldrich GHS Poster GHS_EU_Poster.pdf
class Hazard(TimeStampedModel):
    signal = models.CharField(max_length=10, choices=SIGNALS, blank=True)
    hazard = models.ForeignKey(HStatement, on_delete=models.CASCADE)
    pictograms = models.ManyToManyField(Pictogram, related_name='hazards')
    precautions = models.ManyToManyField(PStatement, related_name='hazards')
    permissions = models.ManyToManyField('SafetyPermission', related_name='hazards', blank=True)
    description = models.TextField(blank=True)
    objects = HazardManager()

    def __str__(self):
        return "{}{}".format('{}: '.format(self.get_signal_display()) if self.signal else '', self.hazard.text)

    def natural_key(self):
        return (self.signal,) + self.hazard.natural_key()

    class Meta:
        unique_together = (('signal', 'hazard'),)


class Sample(TimeStampedModel):
    TYPES = Choices(
        ('', _('')),
        ('chemical', _('Chemical')),
        ('macromolecule', _('Macromolecules')),
        ('geologic', _('Soil, rocks or geologic')),
        (_('Human'), [
            ('human_subject', _('Human Subject')),
            ('human_tissue_alive', _('Human Tissue/Fluid (Living)')),
            ('human_tissue', _('Human Tissue/Fluid')),
            ('human_other', _('Other Human Material')),
        ]),
        (_('Animal'), [
            ('live_animal', _('Live Animal')),
            ('animal_tissue', _('Non-Invasive Animal Tissue/Fluid (Cat A)')),
            ('animal_tissue_invasive', _('Invasive Animal Tissue/Fluid (Cat B+)')),
            ('animal_other', _('Other Animal Material')),
        ]),
        (_('Other Biological'), [
            ('plant', _('Plant or Algae')),
            ('microbe', _('Bacteria, Protozoa or Virus')),
            ('fungi', _('Fungi')),
            ('gmo', _('Genetically Modified Organism')),
            ('bio_other', _('Other biological')),
        ]),
        ('other', _('Other')),
    )
    STATES = Choices(
        ('', _('')),
        ('solid', _('Solid')),
        ('liquid', _('Liquid')),
        ('crystal', _('Crystal')),
        ('gas', _('Gas')),
        ('frozen', _('Frozen')),
        ('suspension', _('Suspension')),
        ('nano', _('Nano-Material')),
        ('fixed', _('Fixed')),
        ('sealed', _('Sealed Radioactive Source')),
        ('other', _('Other State')),
    )
    ETHICS_TYPES = [
        "human_subject", "human_tissue_alive", "human_tissue", "human_other",
        "live_animal", "animal_tissue", "animal_tissue_invasive", "animal_other"
    ]
    owner = models.ForeignKey(User, null=True, related_name='samples', on_delete=models.SET_NULL)
    name = models.CharField("Full Name", max_length=255)
    source = models.CharField("Source of Material", max_length=100, null=True, blank=True)
    extra = models.CharField("Additional Information", max_length=100, null=True, blank=True)
    kind = models.CharField("Type", max_length=100, choices=TYPES, default=None)
    state = models.CharField(max_length=100, choices=STATES, default=None)
    hazard_types = models.ManyToManyField(Pictogram, verbose_name="Hazard Types", related_name='samples')
    hazards = models.ManyToManyField(Hazard, verbose_name="Hazards", related_name='samples', blank=True)
    description = models.TextField(null=True, blank=True)
    is_editable = models.BooleanField(default=True)

    details = models.JSONField(default=dict, null=True, blank=True, editable=False)

    def __str__(self):
        return self.name

    def is_owned_by(self, user):
        """
        Check if the sample is owned by the given user.
        """
        return self.owner == user

    def signal(self):
        for w in ['danger', 'warning']:
            if w in self.hazards.values_list('signal', flat=True).distinct():
                return w
        return ""

    def pictograms(self):
        if self.is_editable:
            return utils.summarize_pictograms(self.hazards, types=self.hazard_types)
        else:
            return utils.summarize_pictograms(self.hazards)

    def all_hazards(self):
        """
        Return all hazards for this sample, including a guess from the hazard types.
        """
        hazards = self.hazards.all() | Hazard.objects.filter(pictograms__in=self.hazard_types.all())
        return hazards.distinct()

    def precautions(self):
        return PStatement.objects.for_hazards(self.hazards.all())

    def permissions(self):
        perms = {
            perm: 'all'
            for perm in
            self.hazards.filter(permissions__isnull=False).values_list('permissions__code', flat=True)
        }
        perms.update(self.details.get('permissions', {}))
        return perms

    def precautions_text(self):
        keywords = self.details.get('keywords', {})
        txt = ""
        for p in self.precautions():
            num_blanks = p.text.count('{}')
            values = re.split(r'\s*[;,|]\s*', keywords.get(p.code, ''))
            full_values = values + ['*'] * (num_blanks - len(values))
            p_txt = p.text.format(*full_values)
            txt += f" - {p_txt}.  \n"
        return txt

    def hazards_text(self):
        txt = ""
        for hz in self.hazards.all():
            txt += "{}.  ".format(hz.hazard.text)
        return txt


class HazardousSubstance(TimeStampedModel):
    name = models.CharField("Name", max_length=255, unique=True)
    description = models.TextField()
    hazards = models.ManyToManyField(Hazard, verbose_name="Hazards", related_name='substances')

    def __str__(self):
        return self.name


class SafetyPermission(TimeStampedModel):
    code = models.SlugField(max_length=50)
    description = models.CharField(max_length=100, blank=True, null=True)
    review = models.BooleanField(_('Show in Review'), default=True)

    def __str__(self):
        return self.description


class SafetyControl(TimeStampedModel):
    TYPES = Choices(
        ('team', _('Team Requirements')),
        ('guide', _('Safety Instructions')),
        ('ppe', _('Personal Protection Equipment')),
        ('form', _('Forms')),
        ('delivery', _('Material Delivery/Removal')),
        ('signage', _('Signage and Permits')),
        ('disposal', _('Disposal and Storage')),
    )
    GROUPS = Choices(
        ('engineering', _('Engineering Controls')),
        ('ppe', _('Personal Protection Equipment')),
        ('inspection', _('Equipment Inspection')),
        ('administrative', _('Administrative Controls')),
        ('other', _('Other Controls')),
    )
    name = models.CharField(max_length=250)
    description = models.TextField()
    category = models.CharField(max_length=20, choices=TYPES, default=TYPES.guide)
    kind = models.CharField(max_length=20, choices=GROUPS, default=GROUPS.engineering)
    active = models.BooleanField(_('Show in Review'), default=True)

    def __str__(self):
        return self.name


class UserRequirement(GenericContentMixin, TimeStampedModel):
    TYPES = Choices(

apps/samples/templates/samples/fields/equipmentreviews.html
{% load dynforms %}
{% load project_tags %}

{% get_equipment_list data=data as equipment %}
<div class="controls " id="{{field.name}}-controls" data-field-name="{{field.name}}">
        <div id="{{field.name}}-list">
            {% for item in equipment %}
            <div id="{{field.name}}-{{forloop.counter0}}-equipment-container" class="p-3 mb-3 bg-white {% if 'rejected' in item.decision %}bg-danger{% endif %}">
                <div class="row">
                    <div class="col-sm-12">
                        <h5 class="my-0 text-condensed"><strong>{{ item.name }}</strong></h5>
                        Manufacturer: <em class="text-body-secondary">{{ item.manufacturer|default:"N/C" }}</em>&emsp;
                        Model: <em class="text-body-secondary">{{ item.model|default:"N/C" }}</em>&emsp;
                        Type: <em class="text-body-secondary">{{ item.type|default:"N/C" }}</em>&emsp;
                        {% if item.description %}
                            <hr class="hr-xs"/>
                            {% if item.description %}<strong>Description:</strong> {{item.description}}{% endif %}
                        {% endif %}
                        <hr class="hr-xs"/>
                    </div>
                </div>
                <div class="row text-condensed" id="{{ field.name }}-{{ forloop.counter0 }}-review">
                    <div class="checkbox checkbox-inline">
                       <label for="{{field.name}}-safe-{{ forloop.counter0 }}"><input name="{{field.name}}.{{forloop.counter0 }}.decision" id="{{field.name}}-safe-{{ forloop.counter0 }}"  class="rejection-cmd"
                        value="safe" {% if 'safe' in item.decision %}checked="checked"{% endif %}
                        type="checkbox">N/A</label>
                    </div>
                    <div class="checkbox checkbox-inline">
                       <label for="{{field.name}}-mechanical-{{ forloop.counter0 }}"><input name="{{field.name}}.{{forloop.counter0 }}.decision" id="{{field.name}}-mechanical-{{ forloop.counter0 }}"  class="decision-cmd"
                        value="mechanical"	{% if 'mechanical' in item.decision %}checked="checked"{% endif %}
                        type="checkbox">Mechanical Inspection</label>
                    </div>
                    <div class="checkbox checkbox-inline">
                       <label for="{{field.name}}-electrical-{{ forloop.counter0 }}"><input name="{{field.name}}.{{forloop.counter0 }}.decision" id="{{field.name}}-electrical-{{ forloop.counter0 }}"  class="decision-cmd"
                        value="electrical"	{% if "electrical" in item.decision %}checked="checked"{% endif %}
                        type="checkbox">Electrical Inspection</label>
                    </div>
                    <div class="checkbox checkbox-inline">
                       <label for="{{field.name}}-csa-{{ forloop.counter0 }}"><input name="{{field.name}}.{{forloop.counter0 }}.decision" id="{{field.name}}-csa-{{ forloop.counter0 }}"  class="decision-cmd"
                        value="csa"	{% if "csa" in item.decision %}checked="checked"{% endif %}
                        type="checkbox">CSA Certification</label>
                    </div>
                    <div class="checkbox checkbox-inline">
                       <label for="{{field.name}}-rejected-{{ forloop.counter0 }}"><input name="{{field.name}}.{{forloop.counter0 }}.decision" id="{{field.name}}-rejected-{{ forloop.counter0 }}" class="rejection-cmd"
                        value="rejected" {% if "rejected" in item.decision %}checked="checked"{% endif %}
                        type="checkbox">Reject</label>
                    </div>
                    <input type="hidden" name="{{ field.name }}.{{ forloop.counter0 }}.name" value="{{ item.name }}">
                </div>
            </div>
            {% empty %}
            <div class="empty">
                <i class="bi-exclamation-triangle text-warning icon-md"></i><br/>
                No equipment requiring Review.
            </div>
            {% endfor %}
        </div>
</div>
<script type="text/javascript">
$(document).on('change', 'input[name$=".decision"]', function () {
    var siblings = $('input[name="' + $(this).attr('name') + '"]').not(this);

    if ($(this).is('.rejection-cmd:checked') || $(this).is('.clear-cmd:checked')) {
        siblings.prop('checked', false)
    }
    if ($(this).is('.decision-cmd:checked')) {
        siblings.filter('.rejection-cmd, .clear-cmd').prop('checked', false);
    }
});

</script>

apps/samples/templates/samples/fields/help.html
{{help}}

apps/samples/templates/samples/fields/one_sample.html
{% load samples_tags %}
{% load static %}
<div class="sample-list-row row " id="sample-{{ sample.pk }}-row">
	<span class="col-3" title="{{ sample.description }}">
		{% if sample.owner == user %}
            <a href="#0" class="sample-edit-command"
               data-modal-url="{% url 'sample-edit-modal' pk=sample.pk %}">{{ sample.name }}</a>
        {% else %}
            {{ sample.name }}
        {% endif %}
	</span>
    <span class="col-2" data-sample-type="{{ sample.kind }}">{{ sample.get_kind_display }}</span>
    <span class="col-1">{{ sample.get_state_display }}</span>
    <span class="col-3">
        {% show_pictograms sample.all_hazards size="xs" stack=False %}
        <input type="hidden"
               name="{{ field_name }}__{{ sample.pk }}__sample"
               value="{{ sample.pk }}"
        >
	</span>
    <div class="col-2">
        <input class="form-control input-sm me-auto text-right"
               aria-label="Quantity"
               type="text" name="{{ field_name }}__{{ sample.pk }}__quantity"
               placeholder=" include number & units"
               value="{{ quantity }}"
        >
    </div>
    <div class="col-1 remove-button text-center" data-sample-pk="{{ sample.pk }}">&nbsp;&nbsp;<i
            class="bi-x-lg text-danger icon-fw  cursor-pointer"></i></div>
</div>

apps/samples/templates/samples/fields/sample-ethics.html
{% load dynforms %}
{% load static %}
{% load samples_tags %}
{% load project_tags %}
{% load jsonify %}

{% spaceless %}
<div class="sample-row py-4 list-group-item {% if rejected %}rejected-sample {% endif %}{% if not sample.is_editable %}reviewed-sample{% else %}pending-sample{% endif %}"
     id="{{ field.name }}-{{ sample.pk }}-ethics-container">
    <div class="d-flex flex-row justify-content-start align-items-start gap-3">
        <div>
            <div class="lead">{{ sample.name }}</div>
            <em>{{ sample.description|default:""|safe }}</em>
        </div>
        <i class="bi-{% if sample.is_editable %}unlock{% else %}lock{% endif %} icon-md icon-fw ms-auto"></i>
    </div>

    <div class="sample-properties">
        <div class="sample-property">
            <div class="text-body-secondary small">Quantity:</div>
            <div>{{ quantity|default:"&hellip;" }}</div>
        </div>
        <div class="sample-property">
            <div class="text-body-secondary small">Type:</div>
            <div>{{ sample.get_kind_display }}</div>
        </div>
        <div class="sample-property">
            <div class="text-body-secondary small">State:</div>
            <div>{{ sample.get_state_display }}</div>
        </div>
        <div class="sample-property">
            <div class="text-body-secondary small">Source:</div>
            <div>{{ sample.source|default:"N/C" }}</div>
        </div>
    </div>

    <div class="row sample-group no-space" id="{{ field.name }}-{{ sample.pk }}-review">
        <div class="field-group-item col-sm-6">
            <label class="form-label" for="{{ field.name }}-decision-{{ sample.pk }}">Decision</label>
            <select class="form-select" name="{{ field.name }}__{{ sample.pk }}__decision"
                    id="{{ field.name }}-decision-{{ sample.pk }}">
                <option></option>
                <option value="ethics" {% if decision == "ethics" %}selected{% endif %}>Valid Ethics
                    Certificate
                </option>
                <option value="protocol" {% if decision == "protocol" %}selected{% endif %}>Valid AUP
                    Certificate
                </option>
                <option value="exempt" {% if decision == "exempt" %}selected{% endif %}>Exempt</option>
                <option value="rejected" {% if decision == "rejected" %}selected{% endif %}>Reject
                </option>
            </select>
        </div>
        <div class="expiry-field field-group-item col-sm-6"
             id="{{ field.name }}-expiry-{{ sample.pk }}-input">
            <label class="form-label" for="{{ field.name }}-expiry-{{ sample.pk }}">Expiry Date</label>
            <input id="{{ field.name }}-expiry-{{ sample.pk }}" aria-label="Expiry Date"
                   placeholder="Expiry date" name="{{ field.name }}__{{ sample.pk }}__expiry"
                   class="form-control date-input"
                   data-date-container="#{{ field.name }}-expiry-{{ sample.pk }}-input"
                   type="text" value="{{ expiry|default:'' }}"
                   {% if decision == "exempt" or decision == "rejected" %}disabled{% endif %}>
        </div>
    </div>
    <input type="hidden" aria-label="Sample ID" name="{{ field.name }}__{{ sample.pk }}__sample"
           value="{{ sample.pk }}">
</div>
{% endspaceless %}

apps/samples/templates/samples/fields/sample-safety.html
{% load dynforms %}
{% load static %}
{% load samples_tags %}
{% load project_tags %}
{% load jsonify %}


<div class="sample-row py-5 list-group-item border-secondary {% if rejected %}rejected-sample {% endif %}{% if not sample.is_editable %}reviewed-sample{% else %}pending-sample{% endif %}"
     id="{{ field.name }}-{{ sample.pk }}-hazards-container"
>
    <div class="d-flex flex-row justify-content-between align-items-center">
        <strong class="fs-5">{{ sample.name }}</strong>
        {% show_pictograms hazards types=sample.hazard_types %}
    </div>

    <span>{{ sample.description|default:""|safe }}</span>

    <div class="sample-properties">
        <div class="sample-property">
            <div class="text-body-secondary small">Quantity:</div>
            <div>{{ quantity|default:"&hellip;" }}</div>
        </div>
        <div class="sample-property">
            <div class="text-body-secondary small">Type:</div>
            <div>{{ sample.get_kind_display }}</div>
        </div>
        <div class="sample-property">
            <div class="text-body-secondary small">State:</div>
            <div>{{ sample.get_state_display }}</div>
        </div>
        <div class="sample-property">
            <div class="text-body-secondary small">Source:</div>
            <div>{{ sample.source|default:"N/C" }}</div>
        </div>
    </div>


    <div class="sample-review-commands">
        {% if not sample.is_editable %}
            <div class="text-primary-emphasis">Reviewed</div>
        {% elif rejected %}
            <div class="text-danger-emphasis">Rejected</div>
        {% else %}
            <div class="text-info-emphasis">In Progress</div>
        {% endif %}

        <div class="sample-review-toolbar">
            {% if sample.is_editable %}
                <a title="Toggle Reject"
                   href="#0"
                   data-bs-toggle="tooltip"
                   class="command-icon reject-sample-command"
                >
                    <i class="bi"></i>
                </a>
                <a title="Review Hazards" href="#0"
                   data-bs-toggle="tooltip"
                   class="command-icon {% if hazards %}highlighted{% endif %}"
                   id="hazard-command-{{ sample.pk }}"
                   data-modal-url="{% url 'sample-hazards'  pk=sample.pk field_name=field.name %}"
                >
                    <i class="bi-exclamation-diamond icon-fw"></i>
                </a>
                <a title="Edit Permissions" href="#0"
                   data-bs-toggle="tooltip"
                   class="command-icon {% if permissions %}highlighted{% endif %}"
                   id="permission-command-{{ sample.pk }}"
                   data-modal-url="{% url 'sample-permissions' pk=sample.pk field_name=field.name %}"
                >
                    <i class="bi-key icon-fw"></i>
                </a>
            {% else %}
                <a title="Sample Locked! Already Reviewed" data-bs-toggle="tooltip">
                    <i class="bi-lock icon-fw text-body-secondary"></i>
                </a>
            {% endif %}
            {% if precautions %}
                <a title="Edit Precautions"
                   class="command-icon {% if precautions.count %}highlighted{% endif %}"
                   data-bs-toggle="collapse"
                   role="button"
                   aria-expanded="false"
                   aria-controls="hazard-precautions-{{ sample.pk }}"
                   href="#hazard-precautions-{{ sample.pk }}"
                >
                    <i class="bi-list-ol icon-fw"></i>
                </a>
            {% endif %}
            <input type="hidden" class="pk-field"
                   name="{{ field.name }}__{{ sample.pk }}__sample"
                   value="{{ sample.pk }}"
            >
            <input type="hidden" class="hazards-field"
                   name="{{ field.name }}__{{ sample.pk }}__hazards"
                   data-saved-hazards="{{ hazards|query_ids|jsonify }}"
                   value="{{ hazards|query_ids|jsonify }}"
                   id="saved-hazards-{{ sample.pk }}"
            >
            <textarea id="permissions-{{ sample.pk }}" class="d-none"
                      class="permissions-field" aria-label="Permissions"
                      name="{{ field.name }}__{{ sample.pk }}__permissions"
            >{{ permissions|jsonify }}</textarea>
            <input id="rejected-{{ sample.pk }}" type="hidden"
                   class="rejection-field"
                   name="{{ field.name }}__{{ sample.pk }}__rejected"
                   {% if rejected %}value="1"{% endif %}
            >
            {% get_precaution_keywords as keywords %}
            <input id="keywords-{{ sample.pk }}"
                   aria-label="Keywords"
                   type="hidden"
                   class="keywords-field" data-keywords-field="keyword-{{ sample.pk }}"
                   name="{{ field.name }}__{{ sample.pk }}__keywords"
                   value='{{ keywords|jsonify }}'
            >
        </div>
    </div>

    <div id="hazard-changes-{{ sample.pk }}" class="alert alert-warning d-none changes-notes">
        <i class="bi-floppy icon-fw" title="Changes have not been saved"></i>&ensp;
        <span class="added"></span>&ensp;
        <span class="removed"></span>
    </div>


    <div class="collapse" id="hazard-precautions-{{ sample.pk }}">
        <table class="table table-sm" style="font-size: 85%;">
            <tr>
                <th colspan="2">Precaution Statement</th>
                <th>Keyword</th>
            </tr>
            {% for p in precautions %}
                <tr>
                    <td class="text-body-secondary">{{ p.code }}</td>
                    <td>{% precaution_text p %}</td>
                    <td>
                        {% if "{}" in p.text %}
                            <input style="width:auto;" placeholder="keyword" type="text"
                                   id="keyword-{{ sample.pk }}-{{ p.code }}"
                                   class="keyword-{{ sample.pk }}"
                                   aria-label="Precaution Keywords"
                                   data-keyword-code="{{ p.code }}"
                                   value="{% precaution_keyword p %}">
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>